# Generated by Django 5.2.1 on 2025-06-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('petitioner', models.CharField(max_length=100)),
                ('defendant', models.CharField(max_length=100)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('issue_date', models.DateField()),
                ('final_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_revenue_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prepaid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payable_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
