# Generated by Django 5.2.1 on 2025-06-09 04:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_issue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='claimed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='payable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='prepaid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tax_revenue_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='issue',
            name='total_days',
            field=models.IntegerField(blank=True, editable=False),
        ),
    ]
