# Generated by Django 5.2.1 on 2025-06-09 06:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bank_alter_issue_petitioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tax_rate',
            field=models.DecimalField(choices=[(Decimal('0.015'), '1.5%'), (Decimal('0.005'), '0.5%')], decimal_places=3, default=Decimal('0.015'), max_digits=4, verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='claimed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
