# Generated by Django 5.2.1 on 2025-06-09 09:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_issue_tax_rate_alter_issue_claimed_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='tax_rate',
            field=models.DecimalField(choices=[(Decimal('0.01'), '1%'), (Decimal('0.005'), '0.5%')], decimal_places=3, default=Decimal('0.05'), max_digits=4, verbose_name='Tax Rate'),
        ),
    ]
