# Generated by Django 5.2.1 on 2025-06-12 06:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_issue_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='मुद्दा नम्बर'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tax_rate',
            field=models.DecimalField(choices=[(Decimal('0.01'), '1%'), (Decimal('0.005'), '0.5%')], decimal_places=3, default=Decimal('0.01'), max_digits=4, verbose_name='Tax Rate'),
        ),
    ]
