# Generated by Django 5.2.1 on 2025-06-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_issue_id_alter_issue_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='final_date_bs',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_date_bs',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
