# Generated by Django 5.2.1 on 2025-06-13 11:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_issue_final_date_bs_issue_issue_date_bs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='final_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='final_date_bs',
            field=models.CharField(help_text='वि.सं मा मिति प्रविष्ट गर्नुहोस् (जस्तै: 2081-12-30)', max_length=20, verbose_name='अन्तिम मिति (वि.सं)'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date_bs',
            field=models.CharField(help_text='वि.सं मा मिति प्रविष्ट गर्नुहोस् (जस्तै: 2081-01-01)', max_length=20, verbose_name='मुद्दा दर्ता मिति (वि.सं)'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tax_rate',
            field=models.DecimalField(choices=[(Decimal('0.01'), '1%'), (Decimal('0.005'), '0.5%')], decimal_places=3, default=Decimal('0.01'), max_digits=4, verbose_name='कर'),
        ),
    ]
