# Generated by Django 5.2.1 on 2025-06-16 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_issue_final_date_alter_issue_final_date_bs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='final_date_bs',
            field=models.CharField(max_length=20, verbose_name='अन्तिम मिति (वि.सं)'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date_bs',
            field=models.CharField(max_length=20, verbose_name='मुद्दा दर्ता मिति (वि.सं)'),
        ),
    ]
