# Generated by Django 5.2.1 on 2025-06-18 05:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_issue_final_date_bs_alter_issue_issue_date_bs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='final_date',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='issue_date',
        ),
        migrations.AlterField(
            model_name='issue',
            name='claimed_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='defendant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='interest_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, verbose_name='ब्याज रकम'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='payable_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, verbose_name='भुक्तानी गर्नुपर्ने रकम'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='petitioner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bank', verbose_name='वादी'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='prepaid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='principal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tax_rate',
            field=models.DecimalField(choices=[(Decimal('0.01'), '1%'), (Decimal('0.005'), '0.5%')], decimal_places=3, default=Decimal('0.01'), max_digits=5, verbose_name='कर'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tax_revenue_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, verbose_name='राजस्व रकम'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=20, verbose_name='कुल रकम'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='total_days',
            field=models.IntegerField(blank=True, editable=False, verbose_name='कुल दिन'),
        ),
    ]
