# Generated by Django 5.2.1 on 2025-06-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_issue_final_date_remove_issue_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='document_date_bs',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='मुद्दा प्रतिवेदन मिति (वि.सं)'),
        ),
        migrations.AddField(
            model_name='issue',
            name='final_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='defendant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='प्रतिवादी'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='शीर्षक'),
        ),
    ]
