# Generated by Django 5.2.1 on 2025-07-08 08:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_issue_document_date_bs_issue_final_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'बैंक', 'verbose_name_plural': 'बैंकहरु'},
        ),
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name': 'थप गणना', 'verbose_name_plural': 'गणना गर्नु होस'},
        ),
        migrations.RemoveField(
            model_name='issue',
            name='document_date_bs',
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_date_bs',
            field=models.CharField(max_length=20, verbose_name='साँवा गणना शुरु (वि.सं)'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tax_rate',
            field=models.DecimalField(choices=[(Decimal('0.010'), '1%'), (Decimal('0.005'), '0.5%')], decimal_places=3, default=Decimal('0.010'), max_digits=6, verbose_name='drt-शुल्क'),
        ),
    ]
